fixed pom file location issue.17

diff --git a/.github/workflows/patient-service.yml b/.github/workflows/patient-service.yml
--- a/.github/workflows/patient-service.yml
+++ b/.github/workflows/patient-service.yml
@@ -57,11 +57,15 @@ jobs:
             sleep 5
           done
 
+      - name: Verify Running Containers
+        run: docker ps -a
+
       # Step 9: Run Post-Deployment Tasks
       - name: Run Post-Deployment Tasks
         run: |
           # Add any post-deployment tasks here, like API tests or health checks
           echo "Running post-deployment tasks..."
+          curl -f http://localhost:4000/actuator/health || (echo "Health check failed" && exit 1)
 
       # Step 10: Push Docker Image to Docker Hub (optional if you want to push to a registry)
       - name: Login to Docker Hub
